# Generated by Django 5.1.2 on 2024-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customuser_comuna_customuser_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
