# Generated by Django 5.1.3 on 2024-11-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_trabajo_is_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
