# Generated by Django 5.1.3 on 2024-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_trabajo_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='pago_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='presupuesto_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='presupuesto_minimo',
            field=models.IntegerField(),
        ),
    ]
